### ISSUE TITLE
Where is the project or solution file ? 

### ISSUE THREAD

**Issue by nullArguments** [chsakell/aspnet-core-signalr-angular#2]
I have downloaded the source and tried to run it using both VSCode and Visual Studio and they keep asking me for project or solution file 
For e.g. 

bash-3.2$ dotnet restore
**MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.**
bash-3.2$ dotnet run
**Couldn't find a project to run. Ensure a project exists in  /aspnet-core-signalr-angular-master.
Or pass the path to the project using --project**
bash-3.2$

**Comment by chsakell** [comment]
[aspnet-core-signalr-angular.csproj](https://github.com/chsakell/aspnet-core-signalr-angular/blob/master/aspnet-core-signalr-angular.csproj)
