### ISSUE TITLE
Can't restore SignalR packages 

### ISSUE THREAD

**Issue by ArsenShkenza** [chsakell/aspnet-core-signalr-angular#3]
Hello, whenever I try dotnet restore I get this : 

Errors in D:\Git\new prove\aspnet-core-signalr-angular\aspnet-core-signalr-angular.csproj
      Unable to resolve 'Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.1'.
      Unable to resolve 'Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
      Unable to resolve 'Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.1 (win7-x64)'.
      Unable to resolve 'Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.1 (win8-x64)'.
      Unable to resolve 'Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.1 (win81-x64)'.

  NuGet Config files used:
      D:\Git\new prove\aspnet-core-signalr-angular\NuGet.Config
      C:\Users\Arsen.Shkenza\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

THANKS IN ADVANCE

**Comment by chsakell** [comment]
@ArsenShkenza apply [this](https://github.com/chsakell/aspnet-core-signalr-angular/commit/a84056f1665ef1b9137eba6eefc2cbd494d88616) change in _NuGet.config_ file and try again.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by ArsenShkenza** [comment]
@chsakell It works now. Thank you, good job. 👍
